### ISSUE TITLE
Moderate status is not honored - questions are still visible

### ISSUE THREAD

**Issue by SauntValerian** [wp3/anspress#241]
Questions that are being held in the moderate status are still being displayed on the Browse Questions page. When clicking on a moderated question, the user gets a *You do not have permission to view this question* error.

This all appears to be a bug somehow.

More discussion on this bug is here http://wp3.in/questions/question/1963/bug-report-questions-held-in-moderation-are-still-visible/

**Comment by rahularyan** [comment]
issue fixed, please check once
