### ISSUE TITLE
The mainpage 'active' tab show no active questions.

### ISSUE THREAD

**Issue by exelian** [wp3/anspress#253]
I'm trying out the plugin and entered some test questions, but they don't show up under the active tab. They do show up in the other tabs (newest, voted etc.). The 'page-8575.php' is a simple custom page which just contains the `[anspress]` shortcode.

Below is the relevant error that showed up in the httpd-error.log.

`[Mon Feb 16 11:34:54 2015] [error] [client 192.168.201.100] WordPress databasefout Unknown column 'mt1.post_id' in 'order clause' bij query SELECT SQL_CALC_FOUND_ROWS  wp_posts.ID FROM wp_posts  INNER JOIN wp_postmeta ON wp_posts.ID = wp_postmeta.post_id WHERE 1=1 AND wp_posts.post_type = 'question' AND ((wp_posts.post_status = 'publish' OR wp_posts.post_status = 'closed' OR wp_posts.post_status = 'moderate' OR wp_posts.post_status = 'private_question')) AND (wp_postmeta.meta_key = '_ap_updated'\nOR wp_postmeta.meta_key = '_ap_updated' ) AND (wp_posts.post_date <= '2015-02-16 23:59:59' OR wp_posts.post_date_gmt <= '2015-02-16 23:59:59') GROUP BY wp_posts.ID ORDER BY case when mt1.post_id IS NULL then wp_posts.post_date else wp_postmeta.meta_value end DESC LIMIT 0, 20 gemaakt door require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/norma/page-8575.php'), the_content, apply_filters('the_content'), call_user_func_array, do_shortcode, preg_replace_callback, do_shortcode_tag, call_user_func, AP_BasePage->ap_base_page_sc, WP_Query->__construct, WP_Query->query, WP_Query->get_posts, referer: http://www.[redacted].eu/vraagenantwoord/?ap_s=&sort=newest`

**Comment by exelian** [comment]
I've updated my wordpress version and this seems to have resolved this issue. I still don't know what cause this issue or how to fix it (other than updating)

**Comment by rahularyan** [comment]
Oh yes, new version of WordPress have some new changes, so I improved AnsPress to make compatible with latest version of WordPress.
BTW: sorry, I missed your issue.
