### ISSUE TITLE
Undefined index notices in Admin Media Library

### ISSUE THREAD

**Issue by Bogardo** [wp3/anspress#255]
I'm getting the following error within the media library page (for every image in the library (8 currently) in the admin. (/wp-admin/upload.php)

`Notice: Undefined index: thumbnail in anspress-question-answer\includes\anspress-user.php on line 961`

Link to src: https://github.com/wp3/anspress/blob/1.4.3/includes/anspress-user.php#L961
```php
// line 961
$orig_file_name = str_replace('-'.$image_meta['sizes']['thumbnail']['width'].'x'.$image_meta['sizes']['thumbnail']['height'], '', $image_meta['sizes']['thumbnail']['file']);	
```

WordPress 4.0.1
Anspress 1.4.3

**Comment by rahularyan** [comment]
This issue will not occur in 2.0-beta, as this function are not used.

**Comment by Bogardo** [comment]
Which doesn't really fix the issue.
When will the 2.0 version be released (stable) and will I be able to upgrade from 1.4.3?

**Comment by rahularyan** [comment]
Current commit in github is stable, But I will wait for users response for some more days.
